### ISSUE TITLE
MambaVision的base版本权重加载

### ISSUE THREAD

**Issue by Qiu-shuang** [simzhangbest/HMT-Unet#4]
我在尝试复现代码中，发现encoder的tiny版本和small版本的权重都能加载成功
`Total model_dict: 558, Total pretrained_dict: 285, update: 278
Not loaded keys: ['norm.weight', 'norm.bias', 'norm.running_mean', 'norm.running_var', 'norm.num_batches_tracked', 'head.weight', 'head.bias']
encoder loaded finished!
Total model_dict: 558, Total pretrained_dict: 266, update: 203
Not loaded keys: ['layers_up.3.blocks.0.conv1.weight', 'layers_up.3.blocks.0.conv1.bias', 'layers_up.3.blocks.0.norm1.running_mean', 'layers_up.3.blocks.0.norm1.running_var', 'layers_up.3.blocks.0.norm1.num_batches_tracked', 'layers_up.3.blocks.0.conv2.weight', 'layers_up.3.blocks.0.conv2.bias', 'layers_up.3.blocks.0.norm2.running_mean', 'layers_up.3.blocks.0.norm2.running_var', 'layers_up.3.blocks.0.norm2.num_batches_tracked', 'layers_up.3.blocks.1.conv1.weight', 'layers_up.3.blocks.1.conv1.bias', 'layers_up.3.blocks.1.norm1.running_mean', 'layers_up.3.blocks.1.norm1.running_var', 'layers_up.3.blocks.1.norm1.num_batches_tracked', 'layers_up.3.blocks.1.conv2.weight', 'layers_up.3.blocks.1.conv2.bias', 'layers_up.3.blocks.1.norm2.running_mean', 'layers_up.3.blocks.1.norm2.running_var', 'layers_up.3.blocks.1.norm2.num_batches_tracked', 'layers_up.3.blocks.2.conv1.weight', 'layers_up.3.blocks.2.conv1.bias', 'layers_up.3.blocks.2.norm1.running_mean', 'layers_up.3.blocks.2.norm1.running_var', 'layers_up.3.blocks.2.norm1.num_batches_tracked', 'layers_up.3.blocks.2.conv2.weight', 'layers_up.3.blocks.2.conv2.bias', 'layers_up.3.blocks.2.norm2.running_mean', 'layers_up.3.blocks.2.norm2.running_var', 'layers_up.3.blocks.2.norm2.num_batches_tracked', 'layers_up.3.downsample.reduction.0.weight', 'layers_up.2.blocks.0.conv1.weight', 'layers_up.2.blocks.0.conv1.bias', 'layers_up.2.blocks.0.norm1.running_mean', 'layers_up.2.blocks.0.norm1.running_var', 'layers_up.2.blocks.0.norm1.num_batches_tracked', 'layers_up.2.blocks.0.conv2.weight', 'layers_up.2.blocks.0.conv2.bias', 'layers_up.2.blocks.0.norm2.running_mean', 'layers_up.2.blocks.0.norm2.running_var', 'layers_up.2.blocks.0.norm2.num_batches_tracked', 'layers_up.2.blocks.1.conv1.weight', 'layers_up.2.blocks.1.conv1.bias', 'layers_up.2.blocks.1.norm1.running_mean', 'layers_up.2.blocks.1.norm1.running_var', 'layers_up.2.blocks.1.norm1.num_batches_tracked', 'layers_up.2.blocks.1.conv2.weight', 'layers_up.2.blocks.1.conv2.bias', 'layers_up.2.blocks.1.norm2.running_mean', 'layers_up.2.blocks.1.norm2.running_var', 'layers_up.2.blocks.1.norm2.num_batches_tracked', 'layers_up.2.blocks.2.conv1.weight', 'layers_up.2.blocks.2.conv1.bias', 'layers_up.2.blocks.2.norm1.running_mean', 'layers_up.2.blocks.2.norm1.running_var', 'layers_up.2.blocks.2.norm1.num_batches_tracked', 'layers_up.2.blocks.2.conv2.weight', 'layers_up.2.blocks.2.conv2.bias', 'layers_up.2.blocks.2.norm2.running_mean', 'layers_up.2.blocks.2.norm2.running_var', 'layers_up.2.blocks.2.norm2.num_batches_tracked', 'layers_up.2.downsample.reduction.0.weight', 'layers_up.1.downsample.reduction.0.weight']
decoder loaded finished!`

但是在加载base版本的encoder时出现问题
`Total model_dict: 640, Total pretrained_dict: 356, update: 319
Not loaded keys: ['levels.2.blocks.0.gamma_1', 'levels.2.blocks.0.gamma_2', 'levels.2.blocks.1.gamma_1', 'levels.2.blocks.1.gamma_2', 'levels.2.blocks.2.gamma_1', 'levels.2.blocks.2.gamma_2', 'levels.2.blocks.3.gamma_1', 'levels.2.blocks.3.gamma_2', 'levels.2.blocks.4.gamma_1', 'levels.2.blocks.4.gamma_2', 'levels.2.blocks.5.gamma_1', 'levels.2.blocks.5.gamma_2', 'levels.2.blocks.6.gamma_1', 'levels.2.blocks.6.gamma_2', 'levels.2.blocks.7.gamma_1', 'levels.2.blocks.7.gamma_2', 'levels.2.blocks.8.gamma_1', 'levels.2.blocks.8.gamma_2', 'levels.2.blocks.9.gamma_1', 'levels.2.blocks.9.gamma_2', 'levels.3.blocks.0.gamma_1', 'levels.3.blocks.0.gamma_2', 'levels.3.blocks.1.gamma_1', 'levels.3.blocks.1.gamma_2', 'levels.3.blocks.2.gamma_1', 'levels.3.blocks.2.gamma_2', 'levels.3.blocks.3.gamma_1', 'levels.3.blocks.3.gamma_2', 'levels.3.blocks.4.gamma_1', 'levels.3.blocks.4.gamma_2', 'norm.weight', 'norm.bias', 'norm.running_mean', 'norm.running_var', 'norm.num_batches_tracked', 'head.weight', 'head.bias']
encoder loaded finished!
Total model_dict: 640, Total pretrained_dict: 337, update: 244
Not loaded keys: ['layers_up.3.blocks.0.conv1.weight', 'layers_up.3.blocks.0.conv1.bias', 'layers_up.3.blocks.0.norm1.running_mean', 'layers_up.3.blocks.0.norm1.running_var', 'layers_up.3.blocks.0.norm1.num_batches_tracked', 'layers_up.3.blocks.0.conv2.weight', 'layers_up.3.blocks.0.conv2.bias', 'layers_up.3.blocks.0.norm2.running_mean', 'layers_up.3.blocks.0.norm2.running_var', 'layers_up.3.blocks.0.norm2.num_batches_tracked', 'layers_up.3.blocks.1.conv1.weight', 'layers_up.3.blocks.1.conv1.bias', 'layers_up.3.blocks.1.norm1.running_mean', 'layers_up.3.blocks.1.norm1.running_var', 'layers_up.3.blocks.1.norm1.num_batches_tracked', 'layers_up.3.blocks.1.conv2.weight', 'layers_up.3.blocks.1.conv2.bias', 'layers_up.3.blocks.1.norm2.running_mean', 'layers_up.3.blocks.1.norm2.running_var', 'layers_up.3.blocks.1.norm2.num_batches_tracked', 'layers_up.3.blocks.2.conv1.weight', 'layers_up.3.blocks.2.conv1.bias', 'layers_up.3.blocks.2.norm1.running_mean', 'layers_up.3.blocks.2.norm1.running_var', 'layers_up.3.blocks.2.norm1.num_batches_tracked', 'layers_up.3.blocks.2.conv2.weight', 'layers_up.3.blocks.2.conv2.bias', 'layers_up.3.blocks.2.norm2.running_mean', 'layers_up.3.blocks.2.norm2.running_var', 'layers_up.3.blocks.2.norm2.num_batches_tracked', 'layers_up.3.downsample.reduction.0.weight', 'layers_up.2.blocks.0.conv1.weight', 'layers_up.2.blocks.0.conv1.bias', 'layers_up.2.blocks.0.norm1.running_mean', 'layers_up.2.blocks.0.norm1.running_var', 'layers_up.2.blocks.0.norm1.num_batches_tracked', 'layers_up.2.blocks.0.conv2.weight', 'layers_up.2.blocks.0.conv2.bias', 'layers_up.2.blocks.0.norm2.running_mean', 'layers_up.2.blocks.0.norm2.running_var', 'layers_up.2.blocks.0.norm2.num_batches_tracked', 'layers_up.2.blocks.1.conv1.weight', 'layers_up.2.blocks.1.conv1.bias', 'layers_up.2.blocks.1.norm1.running_mean', 'layers_up.2.blocks.1.norm1.running_var', 'layers_up.2.blocks.1.norm1.num_batches_tracked', 'layers_up.2.blocks.1.conv2.weight', 'layers_up.2.blocks.1.conv2.bias', 'layers_up.2.blocks.1.norm2.running_mean', 'layers_up.2.blocks.1.norm2.running_var', 'layers_up.2.blocks.1.norm2.num_batches_tracked', 'layers_up.2.blocks.2.conv1.weight', 'layers_up.2.blocks.2.conv1.bias', 'layers_up.2.blocks.2.norm1.running_mean', 'layers_up.2.blocks.2.norm1.running_var', 'layers_up.2.blocks.2.norm1.num_batches_tracked', 'layers_up.2.blocks.2.conv2.weight', 'layers_up.2.blocks.2.conv2.bias', 'layers_up.2.blocks.2.norm2.running_mean', 'layers_up.2.blocks.2.norm2.running_var', 'layers_up.2.blocks.2.norm2.num_batches_tracked', 'layers_up.2.downsample.reduction.0.weight', 'layers_up.1.blocks.0.gamma_1', 'layers_up.1.blocks.0.gamma_2', 'layers_up.1.blocks.1.gamma_1', 'layers_up.1.blocks.1.gamma_2', 'layers_up.1.blocks.2.gamma_1', 'layers_up.1.blocks.2.gamma_2', 'layers_up.1.blocks.3.gamma_1', 'layers_up.1.blocks.3.gamma_2', 'layers_up.1.blocks.4.gamma_1', 'layers_up.1.blocks.4.gamma_2', 'layers_up.1.blocks.5.gamma_1', 'layers_up.1.blocks.5.gamma_2', 'layers_up.1.blocks.6.gamma_1', 'layers_up.1.blocks.6.gamma_2', 'layers_up.1.blocks.7.gamma_1', 'layers_up.1.blocks.7.gamma_2', 'layers_up.1.blocks.8.gamma_1', 'layers_up.1.blocks.8.gamma_2', 'layers_up.1.blocks.9.gamma_1', 'layers_up.1.blocks.9.gamma_2', 'layers_up.1.downsample.reduction.0.weight', 'layers_up.0.blocks.0.gamma_1', 'layers_up.0.blocks.0.gamma_2', 'layers_up.0.blocks.1.gamma_1', 'layers_up.0.blocks.1.gamma_2', 'layers_up.0.blocks.2.gamma_1', 'layers_up.0.blocks.2.gamma_2', 'layers_up.0.blocks.3.gamma_1', 'layers_up.0.blocks.3.gamma_2', 'layers_up.0.blocks.4.gamma_1', 'layers_up.0.blocks.4.gamma_2']
decoder loaded finished!`

我调用设置是这样的：
`@MODEL.register_module
def mynet_tiny(**kwargs):
    model = HMTUNet(depths=[1, 3, 8, 4],
                    num_heads=[2, 4, 8, 16],
                    window_size=[8, 8, 14, 7],
                    dim=80,
                    in_dim=32,
                    mlp_ratio=4,
                    resolution=224,
                    drop_path_rate=0.2,
                    load_ckpt_path='/home/xxx/net/model/pretrain/mambavision_tiny_1k.pth.tar',
                    **kwargs)
    model.load_from()
    return model

@MODEL.register_module
def mynet_small(**kwargs):
    model = HMTUNet(depths=[3, 3, 7, 5],
                    num_heads=[2, 4, 8, 16],
                    window_size=[8, 8, 14, 7],
                    dim=96,
                    in_dim=64,
                    mlp_ratio=4,
                    resolution=224,
                    drop_path_rate=0.2,
                    load_ckpt_path='/home/xxx/net/model/pretrain/mambavision_small_1k.pth.tar',
                    **kwargs)
    model.load_from()
    return model

@MODEL.register_module
def mynet_base(**kwargs):
    model = HMTUNet(depths=[3, 3, 10, 5],
                    num_heads=[2, 4, 8, 16],
                    window_size=[8, 8, 14, 7],
                    dim=128,
                    in_dim=64,
                    mlp_ratio=4,
                    resolution=224,
                    drop_path_rate=0.3,
                    layer_scale=1e-5,
                    layer_scale_conv=None,
                    load_ckpt_path='/home/xxx/net/model/pretrain/mambavision_base_1k.pth.tar',
                    **kwargs)
    model.load_from()
    return model`

encoder中的后两个block权重没有加载成功，我应该如何调整？感谢！

**Comment by simzhangbest** [comment]
你好，这个问题，请仔细debug 网络结构，保持张量对齐
